"""AI Committee typed schema contracts."""

from schemas.audit import (
    AuditCategory,
    AuditFinding,
    AuditReport,
)
from schemas.common import (
    ArtifactId,
    BaseArtifact,
    CommitteeRole,
    CommitteeState,
    Confidence,
    CorrelationId,
    DecisionStatus,
    EventId,
    EventType,
    Hash,
    SessionId,
    Severity,
    Timestamp,
    Version,
    ensure_timezone_aware,
)
from schemas.context import (
    Assumption,
    BudgetContext,
    Constraint,
    ConstraintType,
    ContextDelta,
    Fact,
    OpenQuestion,
    OperationalContext,
    ProblemContext,
    TeamContext,
    TimeContext,
    Unknown,
    apply_context_delta,
)
from schemas.decision import (
    AcceptedRisk,
    DecisionRecord,
    RejectedAlternative,
    ReviewTrigger,
    TradeOffContract,
)
from schemas.defense import (
    ArchitectDefense,
    BaseDefense,
    CritiqueResponse,
    DefenseStance,
    PragmaticDefense,
    ProposalAction,
)
from schemas.epistemic import (
    AssumptionItem,
    ConditionalRecommendation,
    EpistemicCategory,
    EpistemicSection,
    FactItem,
    InferenceItem,
    RecommendationItem,
    UnknownItem,
)
from schemas.events import (
    CriticalErrorPayload,
    EventEnvelope,
    EventPayload,
    PhaseRollbackPayload,
    QuestionRaisedPayload,
    SessionCancelledPayload,
    SessionCreatedPayload,
    UserOverridePayload,
    UserRespondedPayload,
)
from schemas.intervention import (
    AssumptionContestAction,
    BaseHumanIntervention,
    HumanInterventionCommand,
    InterventionType,
    UserAbortCommand,
    UserContestAssumptionCommand,
    UserRequestRevisionCommand,
    UserRespondCommand,
)
from schemas.learning import (
    EpistemicLesson,
    LearningPathStep,
    LearningReference,
    LearningReport,
    ObservedKnowledgeGap,
)
from schemas.proposals import (
    ArchitectProposal,
    BaseProposal,
    CostEstimate,
    EffortLevel,
    PragmaticProposal,
    ReversibilityAssessment,
    ReversibilityLevel,
)
from schemas.synthesis import (
    AlternativeArguments,
    DeliberationSynthesis,
    TradeOffDimension,
)

__all__ = [
    # Common
    "ArtifactId",
    "BaseArtifact",
    "CommitteeRole",
    "CommitteeState",
    "Confidence",
    "CorrelationId",
    "DecisionStatus",
    "EventId",
    "EventType",
    "Hash",
    "SessionId",
    "Severity",
    "Timestamp",
    "Version",
    "ensure_timezone_aware",
    # Context
    "Assumption",
    "BudgetContext",
    "Constraint",
    "ConstraintType",
    "ContextDelta",
    "Fact",
    "OpenQuestion",
    "OperationalContext",
    "ProblemContext",
    "TeamContext",
    "TimeContext",
    "Unknown",
    "apply_context_delta",
    # Proposals
    "ArchitectProposal",
    "BaseProposal",
    "CostEstimate",
    "EffortLevel",
    "PragmaticProposal",
    "ReversibilityAssessment",
    "ReversibilityLevel",
    # Audit
    "AuditCategory",
    "AuditFinding",
    "AuditReport",
    # Defense
    "ArchitectDefense",
    "BaseDefense",
    "CritiqueResponse",
    "DefenseStance",
    "PragmaticDefense",
    "ProposalAction",
    # Synthesis
    "AlternativeArguments",
    "DeliberationSynthesis",
    "TradeOffDimension",
    # Decision
    "AcceptedRisk",
    "DecisionRecord",
    "RejectedAlternative",
    "ReviewTrigger",
    "TradeOffContract",
    # Learning
    "EpistemicLesson",
    "LearningPathStep",
    "LearningReference",
    "LearningReport",
    "ObservedKnowledgeGap",
    # Epistemic Discipline
    "EpistemicCategory",
    "FactItem",
    "AssumptionItem",
    "InferenceItem",
    "UnknownItem",
    "ConditionalRecommendation",
    "RecommendationItem",
    "EpistemicSection",
    # Intervention
    "AssumptionContestAction",
    "BaseHumanIntervention",
    "HumanInterventionCommand",
    "InterventionType",
    "UserAbortCommand",
    "UserContestAssumptionCommand",
    "UserRequestRevisionCommand",
    "UserRespondCommand",
    # Events
    "CriticalErrorPayload",
    "EventEnvelope",
    "EventPayload",
    "PhaseRollbackPayload",
    "QuestionRaisedPayload",
    "SessionCancelledPayload",
    "SessionCreatedPayload",
    "UserOverridePayload",
    "UserRespondedPayload",
]
